name: 'S3 nix cache'
description: 'nix-build with the help of caching to S3'
# Not sure what to do with author name?
author: 'Domen Kožar, Ulrik Strid'
inputs:
  endpoint:
    description: 'S3 endpoint, s3://...'
    required: true
  signingKey:
    description: 'Signing key secret created with `nix key generate-secret`'
    required: true
  awsAccessKeyId:
    description: 'AWS access key ID'
    required: true
  awsSecretAccessKey:
    description: 'AWS secret access key'
    required: true
  skipPush:
    description: 'Set to true to disable pushing build results to the cache'
    default: 'false'
    required: false
  pathsToPush:
    description: 'Whitespace-separated list of paths to push. Leave empty to push every build result.'
    required: false
  pushFilter:
    description: 'Ignored if pathsToPush is set. Regular expression to exclude derivations for the cache push, for example "(-source$|nixpkgs\.tar\.gz$)". Warning: this filter does not guarantee it will not get pushed in case the path is part of the closure of something that will get pushed.'
    required: false
  nixArgs:
    description: 'Extra command-line arguments to pass to nix. If empty, defaults to -j8'
    required: false
branding:
  color: 'blue'
  icon: 'database'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/main/index.js'
